server:
  port: 8081
  servlet:
    context-path: /forReSubmit

mybatis:
  mapperLocations: classpath:mapper/*.xml

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      # 配置数据源类型
      url: jdbc:mysql://localhost:3306/springboottools?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
      username: root
      password: dc01