server:
  servlet:
    context-path: /redis-lock
  port: 8099
spring:
  redis:
  # 找一台多节点都可以访问的服务器部署redis
    host: xx.xx.xx.xx
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
    database: 10