server:
  servlet:
    context-path: /redis-lock
  port: 8082
spring:
  # redis
  redis:
    host: 127.0.0.1
    port: 6379
    redisson:
      # 配置单点模式
      config: classpath:redisson-single-dev.yml